In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
from tensorflow.keras.datasets import mnist

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import MaxPool2D
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dropout 
from tensorflow.keras.layers import Dense

In [2]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [3]:
X_train = X_train.reshape((X_train.shape[0], X_train.shape[1], X_train.shape[2], 1))


In [4]:
X_test = X_test.reshape((X_test.shape[0],X_test.shape[2],X_test.shape[2],1))

In [5]:
print(X_train.shape)
print(X_test.shape)

(60000, 28, 28, 1)
(10000, 28, 28, 1)


In [6]:
X_train = X_train/255
X_test = X_test/255

In [7]:
print(X_train)

[[[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.

In [8]:
print(y_train)
print(y_test)

[5 0 4 ... 5 6 8]
[7 2 1 ... 4 5 6]


In [9]:
model = Sequential()

In [10]:
model.add(Conv2D(32,(3,3),activation='relu', input_shape=(28,28,1)))

In [11]:
model.add(MaxPool2D(2,2))

In [12]:
#adding fully connected layer 
model.add(Flatten())
model.add(Dense(100,activation='relu'))

In [13]:
#adding output layer 
model.add(Dense(10,activation='softmax'))

In [14]:
#compliing the model 
model.compile(loss='sparse_categorical_crossentropy',optimizer='adam', metrics=['accuracy'])

In [15]:
model.fit(X_train,y_train,epochs=10)

Epoch 1/10


1875/1875 [==============================] - 6s 3ms/step - loss: 0.1508 - accuracy: 0.9553
Epoch 2/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0533 - accuracy: 0.9833
Epoch 3/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0331 - accuracy: 0.9901
Epoch 4/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0234 - accuracy: 0.9926
Epoch 5/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0165 - accuracy: 0.9949
Epoch 6/10
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0122 - accuracy: 0.9960
Epoch 7/10
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0081 - accuracy: 0.9974
Epoch 8/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0069 - accuracy: 0.9977
Epoch 9/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0057 - accuracy: 0.9981
Epoch 10/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0

In [16]:
#evaluting the model 

model.evaluate(X_test,y_test)

313/313 [==============================] - 1s 1ms/step - loss: 0.0586 - accuracy: 0.9876


[0.05862059444189072, 0.9876000285148621]